### ISSUE TITLE
email notification doesn't work

### ISSUE THREAD

**Issue by rjycnfynby** [masc3d/btrfs-sxbackup#10]
Tried to use -m flag with it, but didn't received anything. Created configuration file /etc/btrfs-sxbackup.conf:
[Default]
EMAIL_RECIPIENT = 'test@mydomain.com'
It didn't helped either. What would be a right way to debug it?

**Comment by ttshivers** [comment]
Have you installed, configured, and gotten sendmail (or whatever smtp application) to work on its own?

**Comment by rjycnfynby** [comment]
I'm using exim there and it's configured to our internal main SMTP server. Mail sending works.

**Comment by ttshivers** [comment]
Where did you find the syntax for the config file? I looked around in the source code and all I found was this.
```python
    __SECTION_NAME = 'Default'
    __KEY_SOURCE_RETENTION = 'source-retention'
    __KEY_DEST_RETENTION = 'destination-retention'
    __KEY_LOG_IDENT = 'log-ident'
    __key_EMAIL_RECIPIENT = 'email-recipient'
```
It looks like the config file should actually be:
```
[Default]
email-recipient = 'test@mydomain.com'
```

```
usage: btrfs-sxbackup run [-h] [-m [MAIL]] [-li LOG_IDENT]
                          subvolume [subvolume ...]
optional arguments:
  -m [MAIL], --mail [MAIL]
                        enables email notifications. If an email address is
                        given, it overrides the default email-recipient
                        setting in /etc/btrfs-sxbackup.conf
```
According to the documentation, you also should be able to bypass the config file by running "btrfs-sxbackup run -m test@mydomain" to test out the mail feature.

**Comment by masc3d** [comment]
please consider that you will only get an email notification if anything goes wrong (I assumed it goes without saying). 

so for testing, try:
btrfs-sxbackup run <some random path without a backup job> -m <mail>

**Comment by masc3d** [comment]
btrfs-sxbackup is using the sendmail command. it should work with exim.
if it still doesn't, please check if you can send mail on the command line using the sendmail command (exim provides a sendmail wrapper).

**Comment by rjycnfynby** [comment]
Now I see. Pardon me. Somehow I thought it will send me a report even if everything went well. Thank you.
