### ISSUE TITLE
Snapshot retention without transferring possible?

### ISSUE THREAD

**Issue by lkraav** [masc3d/btrfs-sxbackup#11]
I would like to have the retention mechanism and systematic naming conventions for some local snapshots that do not need to be transferred. Is it possible with btrfs-sxbackup?

**Comment by masc3d** [comment]
sure, ssh is optional.

**Comment by lkraav** [comment]
Maybe I haven't understood the documentation. I'm under the impression you always have to specify a source and a destination (local or remote).

**Comment by masc3d** [comment]
you require a source (subvolume to backup) and a destination (subvolume to store backups) but both can be local

**Comment by masc3d** [comment]
you could simply create a local subvolume to store the backups 
`btrfs sub create /mybackup`
initialize a backup job
`btrfs-sxbackup init / /mybackup`
then run
`btrfs-sxbackup run /`

**Comment by lkraav** [comment]
Yep, and I'm doing that across local disks. But I think you're saying it's not possible to skip destination at the moment. Sounds like pull request material.

**Comment by lkraav** [comment]
Actually, I wonder what happens with destination retention static 0 or 1? I guess it would still want to create the subvolume.

**Comment by masc3d** [comment]
First to clarify, a backup without a destination doesn't make sense. Even if your in the same filesystem you will always have a source and a destination.
What you want is to skip the send/receive part as your source and destination are on the same filesystem. Is that correct?

**Comment by masc3d** [comment]
In fact snapshots only are currently not supported. But you could look into https://github.com/digint/btrbk which does support it afaik.

**Comment by lkraav** [comment]
Well, for this low-priority use case, the source subvolume snapshots history perhaps already provide enough of a backup. The destination would simply be for redundancy. But since parent snapshots aren't recursive, 0-redundancy probably doesn't make sense indeed. Thanks for the discussion, I think this can be closed.

**Comment by masc3d** [comment]
Yes, the local source container would basically become the destination, when implemented consistently (and correctly imho). The redundancy would be quite negligible, it's rather the unnecessary performance impact, as you'd still have a lengthy btrfs send/receive operation even though a simple snapshot would suffice.

**Comment by masc3d** [comment]
https://github.com/masc3d/btrfs-sxbackup/commit/2d93dc63ebee92cd067a1af3473c8ee882394fe8

**Comment by lkraav** [comment]
I like this async approach alot https://github.com/csirac2/snazzer#receive-snapshots-from-a-local-filesystem-to-local-backup-media

**Comment by masc3d** [comment]
what's async there..

**Comment by masc3d** [comment]
current implementation (optional destination) is sufficient for local backups, thus closing.
