### ISSUE TITLE
Retention info output spacing is off? 

### ISSUE THREAD

**Issue by lkraav** [masc3d/btrfs-sxbackup#12]
INFO destination :: url [/mnt/backup/srv-conversionready/] retention [2d: 1/d, 2w:3/w, 1m:1/w, 2m:none] compress [False]

Notice the space between 2d: 1/d expression. Is that normal? I would expect to be able to copy paste that as a base for a new expression.

**Comment by masc3d** [comment]
I formatted this for readability. you can still use it, but with quotes eg. "2d: 1/d, 2w:3/w, 1m:1/w, 2m:none"
