### ISSUE TITLE
Timestamp option for local time instead of UTC?

### ISSUE THREAD

**Issue by lkraav** [masc3d/btrfs-sxbackup#14]
I'm foreseeing confusion for my server users trying to compare UTC backup dates to local time sooner or later. Is it a lot of work to make the snapshot naming mechanism configurable?

**Comment by masc3d** [comment]
let's add local time to info output, it's a good idea.

**Comment by masc3d** [comment]
info now contains local time for each snapshot

**Comment by lkraav** [comment]
Thanks. It isn't clear from the README whether this will also alter the snapshot names on the filesystem?

**Comment by masc3d** [comment]
no, it refers to the output of btrfs-sxbackup info

**Comment by masc3d** [comment]
btw. I'm relying on the chronological sorting order, so changing the filename to something where the sorting order is not guaranteed to be chronological (eg. localized time) is not an option.

**Comment by lkraav** [comment]
on this topic, i've been wondering if sxbackup snapshots could gain an rsnapshot-style indicators of which retention rule created them.

rsnapshot creates `weekly.0 weekly.1 daily.0 daily.1 daily.2 hourly.0` etc. directories. sxbackup could do `<timestamp>-utc.12-h.0 <timestamp>-utc.4-d.0 <timestamp>-utc.4-d.1 <timestamp>-utc.4-d.2 <timestamp>-utc.4-d.3 <timestamp>-utc.1-m.0`

**Comment by masc3d** [comment]
btrfs-sxbackup doesn't work like that.  it doesn't have any knowledge about how, when or how often it's invoked or scheduled, this is entirely up to an external setup (eg. cron).
retention is a post process which will "thin out" existing snapshots according to the retention rules defined.

however, I'm currently having a second thought about touching the source volume (as discussed here https://github.com/masc3d/btrfs-sxbackup/issues/15).
even though I originally didn't want to modify the source subvolume in any way, this would allow me to move away from filename based timestamps, opening the door to freely name snapshots and also you to have local timestamps in snapshot names.

still have to investigate a bit further though and may also take a while until it appears in a release.

**Comment by lkraav** [comment]
sounds good, i'm very interested.
