### ISSUE TITLE
Snapshot directory timestamps are constant, should be dynamic

### ISSUE THREAD

**Issue by lkraav** [masc3d/btrfs-sxbackup#15]
```
.sxbackup $ ls -la
total 164
drwxr-xr-x 1 root root 426  8. juuni 08:00 .
drwxr-xr-x 1 root root 158  7. juuni 00:34 ..
-rw-r--r-- 1 root root 214  7. juuni 23:38 .btrfs-sxbackup
drwxr-xr-x 1 root root 158  7. juuni 00:34 sx-20150607-204433-utc
drwxr-xr-x 1 root root 158  7. juuni 00:34 sx-20150607-210208-utc
drwxr-xr-x 1 root root 158  7. juuni 00:34 sx-20150607-230005-utc
drwxr-xr-x 1 root root 158  7. juuni 00:34 sx-20150608-000004-utc
drwxr-xr-x 1 root root 158  7. juuni 00:34 sx-20150608-010004-utc
drwxr-xr-x 1 root root 158  7. juuni 00:34 sx-20150608-020004-utc
drwxr-xr-x 1 root root 158  7. juuni 00:34 sx-20150608-030005-utc
drwxr-xr-x 1 root root 158  7. juuni 00:34 sx-20150608-040004-utc
drwxr-xr-x 1 root root 158  7. juuni 00:34 sx-20150608-050015-utc
```

Everything seems to be created on June 7th on the same minute. The snapshot directory creation date should match the filename.

**Comment by masc3d** [comment]
btrfs subvolumes are not directories. it's the timestamp of the source subvolume (root folder) at the time the snapshot is taken. it's what btrfs does and it makes sense, too..

**Comment by lkraav** [comment]
Can you elaborate on the "static timestamp makes sense" logic for you? Looks like a logic disconnect to me. It is impossible to determine when the snapshot was created if you don't put a timestamp into the subvolume name.

**Comment by masc3d** [comment]
sure. it's basically like a mountpoint. as soon as a volume is mounted the timestamp you see (eg. via ls) will be the one of the mounted volume, not the directory's anylonger.
it's the same here. the timestamp you see is the one of the snapshot subvolume root directory. it's actually the same for all your snapshots as the root directory of your source subvolume didn't change between the backup runs. this behaviour is also not btrfs-sxbackup but *nix related.  I added local time to btrfs-sxbackup info for a more convenient view at backup creation dates.

**Comment by masc3d** [comment]
you could actually simulate a "moving timestamp" by touching your source volume before running the backup eg.
`touch / && btrfs-sxbackup run /`

**Comment by csirac2** [comment]
In my own explorations of this, it's interesting: if you `btrfs send`, `btrfs receive` will set the mtimes on all your snapshots to their creation date in the destination subvol as desired.

I had been toying with the idea of parsing the creation date out of `btrfs subvolume show`, but it's quite slow to invoke this on each snapshot individually. Perhaps we should ask for btrfs-progs to add a new switch which shows creation date in `btrfs subvol list`, there are switches to display nearly every other field displayed by `btrfs subvol show`...

FWIW I've had to mess with source subvols prior to snapshotting anyway, thanks to https://bugzilla.kernel.org/show_bug.cgi?id=95201

**Comment by masc3d** [comment]
https://github.com/masc3d/btrfs-sxbackup/commit/2a701abf7ec15f5fe4bd3bdf9332c95703c82e1e
can you check if this works for you?

**Comment by bhelm** [comment]
I can confirm, its working. Thank you.

**Comment by masc3d** [comment]
thanks for the heads up.
