### ISSUE TITLE
missing license header

### ISSUE THREAD

**Issue by morxa** [masc3d/btrfs-sxbackup#19]
The repository contains the GPLv2 license text, however the source files do not contain any statement of copying permission (license header). According to the [GPL How-To](http://www.gnu.org/licenses/gpl-howto.html), a statement of copying permission is also required, and it would avoid any confusion about the license.

Can you please add a copying statement to the source files?

This is part of an effort to package btrfs-sxbackup for Fedora.

**Comment by masc3d** [comment]
reopened, leaving it to you to close after you checked. I will create a new release as soon as it's closed.

**Comment by morxa** [comment]
Thank you for the fast response! Could you also add this to `setup.py`? Otherwise it looks good!
