### ISSUE TITLE
Error at the end of incremental backup

### ISSUE THREAD

**Issue by MasterPrenium** [masc3d/btrfs-sxbackup#22]
Hi,

I'm getting an error at the end of an incremental backup initiated from the backup server. 

Moreover it seems that the backup is working fine...

> ERROR unsupported operand type(s) for /: 'datetime.timedelta' and 'NoneType'

If it mind, here is my retention settings : "retention = 1d:1, 1w:daily, 1m:1/w, 2m:none"

Best regards,

**Comment by masc3d** [comment]
why `1d:1`?
try `retention = 1w: daily, 1m: 1/w, 2m: none`

**Comment by MasterPrenium** [comment]
Hi, sorry for late reply
Yes I change the settings to yours, same "ERROR". Also set up it to "1d:2, 1w:daily, 1m:1/w, 2m:none" which is my currently backup policy. I'm still getting the "ERROR".

Btw, the retention on destination isn't working : it keeps all my snapshots. Whereas on source (retention is 15) older snapshots are deleted ...

**Comment by masc3d** [comment]
so it works for you now? the exception text actually is the error message.
