### ISSUE TITLE
Invalid script entry point, A callable suffix is required

### ISSUE THREAD

**Issue by basinilya** [masc3d/btrfs-sxbackup#23]
I'm trying to install btrfs-sxbackup on `RHEL7`. It says:

> Installation: pip install btrfs-sxbackup
> Required: python3

I installed `python34` from epel. There's no `pip` for it, so I installed it, like described here: http://stackoverflow.com/a/32771094/447503

`pip3` builds my package, but can't install it:

    [root@wc8rh7 ~]# yum -y install python34
    [root@wc8rh7 ~]# curl https://bootstrap.pypa.io/get-pip.py | python3.4
    [root@wc8rh7 ~]# pip3 install btrfs-sxbackup
    Collecting btrfs-sxbackup
      Downloading btrfs-sxbackup-0.5.9.tar.gz
    Building wheels for collected packages: btrfs-sxbackup
      Running setup.py bdist_wheel for btrfs-sxbackup ... done
      Stored in directory: /root/.cache/pip/wheels/42/28/92/3f60b95db806b9d2e1b3a1a91acdac263dadfaba17a88b1df9
    Successfully built btrfs-sxbackup
    Installing collected packages: btrfs-sxbackup
    Invalid script entry point: <ExportEntry btrfs-sxbackup = btrfs_sxbackup.__main__:None []> for req: btrfs-sxbackup - A callable suffix is required. Cf https://packaging.python.org/en/latest/distributing.html#console-scripts for more information.

  [1]: https://github.com/masc3d/btrfs-sxbackup

**Comment by masc3d** [comment]
I can't replicate this here using pip-7.1.2. could you please post `pip3 --version`

**Comment by basinilya** [comment]
[root@wc8rh7 ~]# pip3 --version
pip 8.1.1 from /usr/lib/python3.4/site-packages (python 3.4)

**Comment by basinilya** [comment]
[btrfs_sxbackup-0.5.9-cp34-none-any.zip](https://github.com/masc3d/btrfs-sxbackup/files/219010/btrfs_sxbackup-0.5.9-cp34-none-any.zip)

**Comment by masc3d** [comment]
try `pip3 install --no-binary :all: btrfs-sxbackup'

**Comment by basinilya** [comment]
It worked!

**Comment by masc3d** [comment]
this is properly fixed in 0.6.2 and newer so you don't need `--no-binary :all:` any longer.
