### ISSUE TITLE
Automate generation of documentation/manpages

### ISSUE THREAD

**Issue by masc3d** [masc3d/btrfs-sxbackup#26]
could probably be implemented and integrated into `setup.py` using classes attached to [this issue](https://bugs.python.org/issue14102) or another solution would be to use [sphinx](http://www.sphinx-doc.org/en/stable/index.html).

**Comment by syntonym** [comment]
I've played a bit with sphinx and [sphinxcontrib.autoprogram](http://pythonhosted.org/sphinxcontrib-autoprogram/) which convertes the argparse parser to rst. You can take a look at it [here](https://github.com/syntonym/btrfs-sxbackup/tree/docs_build/docs/_build/man). There is a bit boilerplate for multiple man pages, which means when a new command is added, one would have to modify that. Alternativly one could simple put everything on a single man page, personally I didn't find that as useful/easy to read.

I've also exported to HTML, but I don't know if you want some docs in html format.

**Comment by masc3d** [comment]
If it can be fully automated, eg. including the `conf.py` it will be good. 
The switches seem to be missing from the `rst`s, but I do like the idea and basic setup. 

if you can provide a fully functional and automated integration with `setup.py` I will certainly merge this.

**Comment by syntonym** [comment]
Do you mean that the documentation is automatically build when a user installs the package locally? Or that you don't have to care about the documentation, i.e. it is automatically build whenenver some change happens, and a user only needs to install the documentation (which is done via the setup.py script)? In the first case sphinx would be a hard requirement, which sounds rather bad.

What exactly do you mean with "including the conf.py"?

I will implement what I think makes sense and then you can take a look.

**Comment by masc3d** [comment]
I meant `conf.py` could probably also be generated, so that the entire mechanism only depends on `argparse` and integrates with `setup.py`.

I'm using `python3 setup.py sdist upload` for releasing a new version and it would be great if all docs, manpages etc. would be generated and included in the distribution in the process.

**Comment by syntonym** [comment]
What about [sphinx](http://www.sphinx-doc.org/en/1.5.1/) and [sphinxcontrib.autoprogram](http://pythonhosted.org/sphinxcontrib-autoprogram/) as dependencies (for building the docs, ofcource not for endusers)? I guess the logic isn't too complex and could be extracted into a separate script, but if in the future anything should change sphinx has lots of features and is well documented.

**Comment by masc3d** [comment]
I don't see an issue with adding deps to the build toolchain

**Comment by syntonym** [comment]
I can't really find a way to install man pages when installing via pip. I think pip transforms to wheels and wheels no longer can install to arbitrary locations. When packaged for package managers for distributions these could install the manpages. Do you still want to merge?

**Comment by masc3d** [comment]
never tried it. does this restriction apply even when installing with `sudo`/root?

**Comment by masc3d** [comment]
I have seen `pip` packages which install man pages, so there has to be a way. It has been discussed [here](https://github.com/pypa/packaging-problems/issues/72) eg..

**Comment by syntonym** [comment]
Hm, you are right. [This issue](https://bitbucket.org/pypa/wheel/issues/92/bdist_wheel-makes-absolute-data_files) says that wheels can't handle absolute data files and the [changelog of pip](https://pip.pypa.io/en/stable/news/) says "Build Wheels prior to installing from sdist, caching them in the pip cache directory to speed up subsequent installs. (PR #2618)". But installing one of the examples you linked via pip installs the man pages, so I guess something changed. Sorry for that.

**Comment by masc3d** [comment]
Merged into `master`, thanks!
