### ISSUE TITLE
btrfs-sxbackup assumes bash as remote shell

### ISSUE THREAD

**Issue by yuergen** [masc3d/btrfs-sxbackup#27]
If the backup user's shell is not bash btrfs-sxbackup can not initialize a remote a backup job.

I did not test other commands than init. These are possibly affected as well.

Changing the remote command call to use a specific shell (/bin/bash?) could solve this, without breaking existing installations (assuming they have /bin/bash, which is safe to assume).

**Comment by masc3d** [comment]
it's not that easy. see the accepted answer of this [issue](http://serverfault.com/questions/162018/force-ssh-to-use-a-specific-shell).

if you have a good idea to get around it, let me know. until then it's probably better to simply have bash as a default for the user invoking btrfs-sxbackup.

**Comment by masc3d** [comment]
There's a way to implement this, but only by escaping/quoting manually which I consider ugly and not worth the benefit of not having to set an appropriate shell for the user running the backup. Feel free to reopen this if you have a suggestion for a better solution.

**Comment by masc3d** [comment]
I updated the requirements in the readme to include those constraints.

**Comment by yuergen** [comment]
I did not realize this is actually a problem which is not easily solvable. Sadly I have no idea on how to approach it in a useful manner.

It would be possible to let the user choose a remote shell during the init of the job. That would make it necessary to maintain multiple sets for the remote commands, which makes it a bad idea.

Adding the requirements on the shell to the read me is possibly the best solution.

Thanks!
