### ISSUE TITLE
Yearly options for retention are missing

### ISSUE THREAD

**Issue by yuergen** [masc3d/btrfs-sxbackup#28]
More prolonged backup schemes would profit from the possibility for yearly retention policies.

Example: `-dr "[...] 1y:1/y, 5y:none"`

Emulating this via `12m:1/12m, 60m:none` does not work.

Having q as descriptor for quarterly could be useful for certain use cases.

**Comment by masc3d** [comment]
Thanks, I implemented the yearly literal, for quarterly you can now specify eg. `1/4m`. It's available in `0.6.6`.

**Comment by yuergen** [comment]
Thank you for this enhancement! :)
