### ISSUE TITLE
v0.6.8 always transferring full snapshots

### ISSUE THREAD

**Issue by zlarf** [masc3d/btrfs-sxbackup#32]
Hi.

Since upgrading from v.0.6.4 to v0.6.8, incremental backups do not work. Full snapshots are always sent without any warning message.

With a quick look it seems to me, that the culprit is commit 8e54abc8e0ae12d. 

It looks like that with this:
`if self.destination is not None:
   [snip]
else:
    source_parent_path = os.path.join(self.source.container_subvolume_path, str(self.source.snapshots[0].name))
`
...the source_parent_path is only set if there are no destination snapshots.

**Comment by masc3d** [comment]
indeed, a careless mistake with severe consequences. thanks for pointing it out, fix is on the way.

**Comment by masc3d** [comment]
pushed `0.6.9` to pypi

**Comment by zlarf** [comment]
Nice, a quick fix. ...and thanks for the great software!
