### ISSUE TITLE
snapshots not getting purged

### ISSUE THREAD

**Issue by akorinek** [masc3d/btrfs-sxbackup#33]
I've got the following snapshots:

drwxrwxrwx 1 root root 108 Jun 11 06:21 sx-20160609-133614-utc
drwxrwxrwx 1 root root 108 Jun 13 12:17 sx-20160613-161358-utc
drwxrwxrwx 1 root root 108 Jun 15 10:26 sx-20160615-142611-utc
drwxrwxrwx 1 root root 108 Jun 20 02:30 sx-20160620-063002-utc
drwxrwxrwx 1 root root 108 Jun 21 03:03 sx-20160621-063003-utc
drwxrwxrwx 1 root root 108 Jun 22 02:36 sx-20160622-063004-utc
drwxrwxrwx 1 root root 108 Jun 22 16:53 sx-20160622-193254-utc
drwxrwxrwx 1 root root 108 Jun 24 02:31 sx-20160624-063002-utc
drwxrwxrwx 1 root root 108 Jun 25 02:41 sx-20160625-063003-utc
drwxrwxrwx 1 root root 108 Jun 26 02:30 sx-20160626-063002-utc
drwxrwxrwx 1 root root 108 Jun 27 02:30 sx-20160627-063002-utc
drwxrwxrwx 1 root root 108 Jun 28 02:33 sx-20160628-063002-utc
drwxrwxrwx 1 root root 108 Jun 29 02:32 sx-20160629-063002-utc
drwxrwxrwx 1 root root 108 Jun 30 02:35 sx-20160630-063001-utc
drwxrwxrwx 1 root root 108 Jul  1 02:30 sx-20160701-063003-utc
drwxrwxrwx 1 root root 108 Jul  2 02:30 sx-20160702-063002-utc
drwxrwxrwx 1 root root 108 Jul  3 02:30 sx-20160703-063002-utc
drwxrwxrwx 1 root root 108 Jul  4 02:30 sx-20160704-063002-utc

When I run btrfs-sxbackup purge on this, I get:

 btrfs-sxbackup purge /mnt/backuppool/
INFO btrfs-sxbackup v0.6.6
INFO source :: url [ssh://root@192.168.3.1:/mnt/storage/] container [.sxbackup/] retention [3] compress [False]
INFO destination :: url [/mnt/backuppool/] retention [2d: 1/d, 2w:3/w, 1m:1/w, 2m:none] compress [False]
INFO source :: retrieving snapshots
INFO destination :: retrieving snapshots
INFO destination :: removing 1 snapshot due to retention [2d: 1/d]: sx-20160622-193254-utc

Why is this not deleting more snapshots according to the retention policy?

**Comment by masc3d** [comment]
seems correct to me. what did you expect/want it to purge?

**Comment by akorinek** [comment]
You  are right, I think I read the docs wrong about how the retention policies work. I assumed it would mean: "For 2 days, keep one a day, for 2 weeks keep 3 per week, etc".
