### ISSUE TITLE
arcfour support for ssh

### ISSUE THREAD

**Issue by akorinek** [masc3d/btrfs-sxbackup#34]
Hi,

I've seen slowdowns in the transfer of the snapshots between the backupserver and the client. Investigation into why I only got around 30 MB/s over a gigabit ethernet line resulted in the finding that the ssh server causes heavy CPU load. Using the arcfour parameter for ssh results in full gigabit speed transfers. Encryption is not important for this use case, since both computers communicate over a cross-over cable.

**Comment by masc3d** [comment]
yes. if trading off security for performance/throughput for a specific host makes sense, you can [set this up on the `ssh`client side](http://man.openbsd.org/ssh_config).

**Comment by masc3d** [comment]
does this resolve the issue for you?

**Comment by masc3d** [comment]
closed due to inactivity.
