### ISSUE TITLE
Complex retention expressions do not seem to work

### ISSUE THREAD

**Issue by bhelm** [masc3d/btrfs-sxbackup#4]
Nice to see so much progress on this project, thanks!
i have tried the advanced retention feature, but it does not seem to work for me.

here is my .btrfs-sxbackup file on destination:
```
root@backup:/home/backup/mariadb# cat .btrfs-sxbackup 
[Destination]
uuid = 9b7ea342-ac06-4162-b1f0-4d378d1daa86
source = ssh://root@whatever.org:/mariadb/
source-container = .sxbackup/
retention = 2w:24/d, 1m:4/d, 6m:daily, 7m:none
compress = True
```
and here is the log output from my last run:
```
2015-03-20T17:56:23.4655+01:00 []: btrfs-sxbackup[4447] INFO btrfs-sxbackup v0.5.4
2015-03-20T17:56:23.8235+01:00 []: btrfs-sxbackup[4447] INFO source :: url [ssh://root@whatever.org:/mariadb/] container [.sxbackup/] retention [1] compress [True]
2015-03-20T17:56:23.8237+01:00 []: btrfs-sxbackup[4447] INFO destination :: url [/home/backup/mariadb/] retention [2w:24/d, 1m:4/d, 6m:daily, 7m:none] compress [True]
2015-03-20T17:56:23.8238+01:00 []: btrfs-sxbackup[4447] INFO preparing environment
2015-03-20T17:56:24.5984+01:00 []: btrfs-sxbackup[4447] INFO source :: retrieving snapshot names
2015-03-20T17:56:24.7998+01:00 []: btrfs-sxbackup[4447] INFO destination :: retrieving snapshot names
2015-03-20T17:56:24.8485+01:00 []: btrfs-sxbackup[4447] INFO source :: creating snapshot
2015-03-20T17:56:27.6031+01:00 []: btrfs-sxbackup[4447] INFO source :: transferring snapshot
2015-03-20T18:11:55.0481+01:00 []: btrfs-sxbackup[4447] INFO source :: removing 1 snapshot due to retention [1]: sx-20150320-111915-utc
2015-03-20T18:11:56.3179+01:00 []: btrfs-sxbackup[4447] INFO backup sx-20150320-165624-utc created successfully in 00:15:32
```
it does not try to remove any snapshots from the destination. here is the full list of my destination snapshots:
http://www.pastebin.ca/2961717

i would expect that retention would remove all but one from the sx-20150219-* snapshots.

most of these snapshots were created by btrfs-sxbackup 0.3*. i have deleted all but these snapshots and did a btrfs-sxbackup init with the existing destination path.

Thank you!

**Comment by masc3d** [comment]
hello,
glad you like it )
1m(onth) translates to 30 days here, so the expression 1m:4/d would apply to backups older than 2015-02-18 16:56:24 based on the execution for this run. looks ok to me so far?

**Comment by bhelm** [comment]
i think my rule boils down to: 0-14 days: 24/day, 15-30 days: 4/day, 31-180 days: 1/day, >180 days: none
my problem is hat the 15-30 days range is not 4/day. do i understand something wrong?

retention removed some snapshots over the weekend, grep'ed log output and remaining snapshots here:
http://www.pastebin.ca/2962707

some things i noticed
1. 2w:24/d deleted a ~30 days old snapshots but not that ones that are >14 days old (and there are plenty)
2. for sx-20150220-* are two snapshosts left. it deleted all the others, but left those two. its possible that the last one will get removed some time today, i will watch for it.
3. its deleting them one-by-one. i would expect to see whole days getting removed at once, but i think you are processing it in a "now() - 60*60*24*days" manner. is that correct?

**Comment by masc3d** [comment]
yes it's operating on timedeltas.

I suppose you did not understand it correctly yes. your rules translate to:
- backups older than 2 weeks: keep 24/day (~one per hour)
- backups older than 1 month: keep 4/day
etc.

anything before the first interval (2 weeks here) remains unprocessed.

**Comment by bhelm** [comment]
ok, i have read it wrong
```
  -sr SOURCE_RETENTION, --source-retention SOURCE_RETENTION
                        expression defining which source snapshots to
                        retain/cleanup. can be a static number (of backups) or
                        more complex expression like "1d:4/d, 1w:daily,
                        2m:none" literally translating to: "1 day from now
                        keep 4 backups a day, 1 week from now keep daily
                        backups, 2 months from now keep none"
```
the "1 day from now keep 4 backups a day" sounded like "from now to one day". maybe its just my bad understanding.
Here is my idea on how to improve the description:
```
  -sr SOURCE_RETENTION, --source-retention SOURCE_RETENTION
                        Expression defining which source snapshots to
                        retain. Can be a static number (of backups) or
                        more complex expression. I.e. "1d:4/d, 1w:daily,
                        2m:none" literally translating to: "starting from 
                        1 day to one week, keep 4 backups a day, from 
                        1 week to 2 months keep daily backups and 
                        after 2 months from now on keep none"
```

**Comment by masc3d** [comment]
"from now to 1 day"  is actually "1 day from now" inverted..
thanks for the recommendation, but imho the description is ok :)

**Comment by bhelm** [comment]
Yeah, im not saying that it is wrong. I just say it could be more clear. Your description on post 3 is very easy to understand :)

Anyways, thank you for explaining it to me. The retention feature is great! Its really the cherry on the pie.

**Comment by masc3d** [comment]
okay ) if you have more suggestions about useful features feel free to email me.
