### ISSUE TITLE
Multiple source subvolumes 

### ISSUE THREAD

**Issue by omfdzg** [masc3d/btrfs-sxbackup#40]
Hi, masc3d 

is it possible to add multiple source volumes for single destination, I went trough this article [https://github.com/masc3d/btrfs-sxbackup/issues/9](Single Source & Multiple Destinations #9 ) and some similar hack would be very appreciated.

Thank you.

**Comment by masc3d** [comment]
I don't see how this would make sense, but maybe it's a misunderstanding in terminology. Could you please describe a specific use case?

**Comment by omfdzg** [comment]
sure, I have multiple btrfs filesystems/subvolumes on my source server 
btrfs fi show 
Label: 'root'  uuid: 672826ad-18c2-415f-ae8e-2ec513b2fb55
	Total devices 1 FS bytes used 18.32GiB
Label: 'pool'  uuid: 9d2d24ff-ee67-4034-8671-3c9ffcc6c17a
	Total devices 2 FS bytes used 6.98TiB
Label: 'bpool'  uuid: d41b77ba-d56c-4a91-8320-21a347505ff5
	Total devices 1 FS bytes used 3.15TiB
each of this filesystems , contain multiple subvolumes, for example by default root subvolume contain @ and @home 

I would like to backup each of these subvolumes to alternate server 
btrfs-sxbackup init / ssh://root@192.168.34.3:/backup
INFO preparing source and destination environment
INFO source :: url [/] container [.sxbackup/] retention [3] compress [False]
INFO destination :: url [ssh://root@192.168.34.3:/backup/] retention [2d: 1/d, 2w:3/w, 1m:1/w, 2m:none] compress [False]
INFO initialized successfully

not as lucky with anoyher subvolume

**Comment by masc3d** [comment]
Btrfs cannot send/receive nested subvolumes..

**Comment by masc3d** [comment]
Why would you want to split `home` into a btrfs subvolume anyhow?

**Comment by digitalcircuit** [comment]
@masc3d It allows making snapshots of ```home``` separately from the entire system.  I'm not sure if that's the best reason, but it's worthwhile noting that ```@``` and ```@home``` is Ubuntu's default BTRFS layout for the root disk.

I didn't think of trying ```btrfs-sxbackup``` on the root volume, I've just backed up ```@``` and ```@home``` separately.

*Rough default of ```/etc/fstab``` in an Ubuntu 16.04 installation, names aside:*
```
/dev/mapper/system_ssd-root /               btrfs   defaults,subvol=@,[...]
/dev/mapper/system_ssd-root /home           btrfs   defaults,subvol=@home,[...]
```

**Comment by masc3d** [comment]
yes, I actually removed my question, as I presumed you will have a good reason to have the split.

you can backup both to the same destination filesystem, but not the same destination subvolume.
for your setup this would probably work:
```
btrfs-sxbackup init / ssh://root@192.168.34.3:/backup
btrfs-sxbackup init /home ssh://root@192.168.34.3:/backup-home
```
the destination subvolumes will be created automatically.

**Comment by masc3d** [comment]
of course you could also have some nested subvolumes on the destination for sturcturing like `/backup/root` `/backup/home`.

But each source subvolume requires a dedicated destination subvolume for backup.

**Comment by omfdzg** [comment]
Oh, my bad, yes with nested subvolumes your script works great.
Thank you!

**Comment by masc3d** [comment]
you're welcome )
