### ISSUE TITLE
source retention = 0 does not delete local snapshot after transfer

### ISSUE THREAD

**Issue by madsl** [masc3d/btrfs-sxbackup#45]
If you define source retention = 0, btrfs-sxbackup does not delete the source snapshot created after finishing the transfer.

It's useful to have source retention = 0 when you're taking backups of nocow stuff where you dont want to retain snapshots locally (since they make noCoW files effectively CoW again), and for me it's not that big of a deal that you'll have to transfer the whole thing every time you run a backup of noCoW stuff.

**Comment by masc3d** [comment]
That's true. The latest snapshot is always preserved (on purpose).

If you just want plain `nocow` backups without local snapshots, `btrfs-sxbackup` seems like the wrong tool to use. I would suggest looking into either [rsnapshot](http://rsnapshot.org) or [rdiff-backup](http://www.nongnu.org/rdiff-backup), which should perfectly suit your needs.

Please close this issue if that resolves it.

**Comment by madsl** [comment]
Yeah, I won't go to the barricades for this feature :P You're right that other tools might be better for this kind of backups, especially when considering that making snapshots of noCoW stuff in theory introduces CoW-behaviour when snapshotting, thus making the backup not completely unobtrusive...
