### ISSUE TITLE
Off by one at retention

### ISSUE THREAD

**Issue by JanWelker** [masc3d/btrfs-sxbackup#47]
It looks like the retention setting is off by one. I set 3 for source retention and 6 for destination retention. But it keeps 4 and 7 snapshots:

```
[root@thales ~]# btrfs-sxbackup info /mnt/data/processing/
INFO btrfs-sxbackup v0.6.11
INFO source :: retrieving snapshots
INFO destination :: retrieving snapshots
   UUID                   0844e6ba-3620-487a-a379-6ad20b58d797
   Compress               True
   Source URL             /mnt/data/processing
   Source info            Linux 4.12.13-300.fc26.x86_64 #1 SMP Thu Sep 14 16:00:38 UTC 2017 GNU/Linux, btrfs-progs v4.9.1
   Source container       .sxbackup
   Source retention       3
   Source snapshots       sx-20171005-094616-utc: Thu Oct  5 11:46:16 2017 (+0200)
                          sx-20171005-094526-utc: Thu Oct  5 11:45:26 2017 (+0200)
                          sx-20171005-094443-utc: Thu Oct  5 11:44:43 2017 (+0200)
                          sx-20171005-094313-utc: Thu Oct  5 11:43:13 2017 (+0200)
   Destination URL        ssh://root@archive.wth.in:/mnt/data
   Destination info       Linux 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 GNU/Linux, btrfs-progs v4.9.1
   Destination retention  6
   Destination snapshots  sx-20171005-094616-utc: Thu Oct  5 11:46:16 2017 (+0200)
                          sx-20171005-094526-utc: Thu Oct  5 11:45:26 2017 (+0200)
                          sx-20171005-094443-utc: Thu Oct  5 11:44:43 2017 (+0200)
                          sx-20171005-094313-utc: Thu Oct  5 11:43:13 2017 (+0200)
                          sx-20171005-094152-utc: Thu Oct  5 11:41:52 2017 (+0200)
                          sx-20171005-094048-utc: Thu Oct  5 11:40:48 2017 (+0200)
                          sx-20171005-093907-utc: Thu Oct  5 11:39:07 2017 (+0200)
```

**Comment by masc3d** [comment]
yes, that is due to the latest snapshot being always preserved and not considered for anything retention/cleanup related. but I do agree, it would be more intuitive to do so on static retention expressions.

**Comment by masc3d** [comment]
on second thought and considering eg. `purge`, the latetst snapshot is consistently preserved / ignored for anything retention related. so eg. `purge -sr 2w` will also intentionally preserve the latest snapshot, even if it's older than 2 weeks. 

I prefer to keep this consistent, even though it may appear confusing at first glance.

**Comment by masc3d** [comment]
If you have further comments or ideas let me know, otherwise please close this issue

**Comment by JanWelker** [comment]
> I prefer to keep this consistent, even though it may appear confusing at first glance.

I agree. But it would make sense to mention this in the documentation. I will send you a pull request next week with my thoughts for additional items in the docu.

Cheers,
Jan

**Comment by lkraav** [comment]
> yes, that is due to the latest snapshot being always preserved and not considered for anything retention/cleanup related. but I do agree, it would be more intuitive to do so on static retention expressions.

I agree, this would be useful in documentation, at least in README.md. @JanWelker did you ever file that PR?
