### ISSUE TITLE
Snapshot directories

### ISSUE THREAD

**Issue by gkzsolt** [masc3d/btrfs-sxbackup#49]
Hi,
I have seen and tried this program recently, after making plans for a backup with btrfs. The code seems to be very thoroughly written, congratulations. I have a few questions, though.
I'll backup the root fs of several machines to one place. For a test, I started with a destination on the local host with the following command:
`# btrfs-sxbackup init / /.sxbackup`
(I guess `/.sxbackup` can be any different subvolume, but I think it does not matter at this stage.)
The command above created 2 new subvolumes:
- `/sx-20180409-162320-utc` and
- `/.sxbackup/sx-20180409-162320-utc`
for the source and destination, presumably. A new
`# btrfs-sxbackup run /`
command created other 2 files. My first question is: can I set a directory for the source snapshots? Otherwise they are going to pile up all on `/`, what doesn't look nice.
The second question relates to the `subvolume` argument (of `run` and other subcommands). It is vaguely defined as "source or destination subvolume. local path or SSH url". Is that enough? What if the source of one job matches the destination of another? For example, I am backing up from machine2 to local/path1, then from local/path1 to machine3? 
I am missing a list of backup jobs. I've seen that they are listed in /.sxbackup/.btrfs-sxbackup, but it still doesn't answer the question and I don't know if it is generally true. This should be documented (as the backup process, what each command is doing, what subvolumes are created, deleted, a.s.o.)
Thanks for helping,
   Zsolt

**Comment by masc3d** [comment]
> The code seems to be very thoroughly written, congratulations

thank you.

you're right, conceptually it's not well documented atm which can lead to misunderstandings.

`.sxbackup` is actually the default source container for local snapshots and should not be used as a destination. there's currently no sanity check preventing this. 

I believe it would be best to manually clean this up (remove all subvolumes that have been created) and start over using a dedicated destination subvolume of your own.

`.sxbackup` will be created on `init`  for storing the backup job configuration and local snapshots.
If all you need is local snapshots you can actually omit the destination entirely.

here's some examples

### Local snapshots only

`init /`

### Push backups locally

`init / /mnt/backup/host1`

### Push backups remotely

`init / ssh://root@destination/mnt/backup/host1`

### Pull backups remotely

`init ssh://root@source/ /mnt/backup/host1`

When using a push backup setup you invoke `run` on the source machine with the source volume as parameter

When using a pull backup setup you invoke `run` on the destination machine with the destination volume as parameter.

hence the ambiguity you've been pointing out.

`btrfs-sxbackup` only maintains individual backup jobs and has no intent of providing comprehensive management.

eg. you could run or schedule multiple jobs at once using `run /mnt/backup/*`

**Comment by gkzsolt** [comment]
Thank you. I think the choice of a fixed name/path `/.sxbackup` for the local container is a bit unfortunate. It doesn't provide enough flexibility. But thanks anyway.

**Comment by masc3d** [comment]
enough flexibility for?

**Comment by gkzsolt** [comment]
I am mounting my root fs as a subvolume (called '@'), and would like to keep my local snapshots in a subvolume outside of @, at the same level (parent of 5, if I remember correctly). Can this be achieved with sxbackup?

**Comment by masc3d** [comment]
yes, you can move `.sxbackup` after `init` and amend `.btrfs-sxbackup` accordingly.

however, this may imply breakage of some features relying on this convention (which are not implemented yet and you may not require, see enhancement issues)

all core operations should remain intact.
