### ISSUE TITLE
Pre/post-snapshot command for pull jobs

### ISSUE THREAD

**Issue by dev-zero** [masc3d/btrfs-sxbackup#5]
When pulling a backup it would be nice to be able to specify a command to be executed on the remote machine before taking the snapshot (to get a database in a consistent state for example).

**Comment by masc3d** [comment]
would this really offer much more than just adding to the cron commandline? eg. ssh root@<host> <precmd> && btrfs-sxbackup run <job> && ssh root@<host> <postcmd>

**Comment by dev-zero** [comment]
Good question. It would avoid having to write a custom wrapper script which does something like:

```bash
ssh root@[host] [precmd] || exit $?
btrfs-sxbackup run [job]
retval_backup=$?
ssh root@[host] [postcmd] || exit $?
exit $retval_backup
```

On the other hand you might then also be asked to implement something like:
* block further backup runs if pre- or post-command failed (since you are probably in an inconsistent state then)
* provide non-fatal pre-/post-backup hooks
etc.

So I would totally understand if you decide not to implement any of this.

**Comment by masc3d** [comment]
yes I'm thinking it would be a bit out of scope for a filesystem based backup solution. specific applications which may suffer consistency issues with snapshots should rather have a dedicated backup setup.
