### ISSUE TITLE
No way to disable compression

### ISSUE THREAD

**Issue by neilbags** [masc3d/btrfs-sxbackup#53]
There is no inverse of the '-c' option, so you can't disable compression without deleting the Compression line out of the config file on the source and destination.

Will try to make a pull request when I get a chance

**Comment by masc3d** [comment]
actually there is.

` btrfs-sxbackup update --help`
```
  -nc, --no-compress    disable compression during transmission
```

is just readme being outdated.

**Comment by masc3d** [comment]
should be ok now. 0ee6d250acf06df0b9dfae96c3102532fb1a0b81
