### ISSUE TITLE
Backup not working unexpected EOF in stream

### ISSUE THREAD

**Issue by 6485im43** [masc3d/btrfs-sxbackup#56]
Hello,

i'm using btrfs sxbackup over one year now to backup my nas to another server without any errors.
Since the last two weeks I'm getting the following error message:

```
INFO btrfs-sxbackup v0.6.11
INFO source :: url [/mnt/storage01/data/] container [.sxbackup/] retention [1] compress [False]
INFO destination :: url [ssh://nas02:/mnt/storage01/data/] retention [40] compress [False]
INFO preparing environment
INFO source :: retrieving snapshots
INFO destination :: retrieving snapshots
INFO source :: creating snapshot
INFO source :: transferring snapshot
ERROR source :: Command ['ssh', '-o', 'ServerAliveInterval=5', '-o', 'ServerAliveCountMax=3', 'nas02', 'ionice -c3 btrfs receive "/mnt/storage01/data/"'] failed with error code 1 (At snapshot .temp.da96dc2032cb4320a1d88771f9b4ae05
ERROR: unexpected EOF in stream.)
ERROR source :: Command ['bash', '-c', 'ionice -c3 btrfs send -p "/mnt/storage01/data/.sxbackup/sx-20190825-230640-utc" "/mnt/storage01/data/.sxbackup/.temp.da96dc2032cb4320a1d88771f9b4ae05"'] failed with error code 1 (At subvol /mnt/storage01/data/.sxbackup/.temp.da96dc2032cb4320a1d88771f9b4ae05
ERROR: send ioctl failed with -5: Input/output error)
INFO destination :: removing subvolume [/mnt/storage01/data/.temp.da96dc2032cb4320a1d88771f9b4ae05]
INFO source :: removing subvolume [/mnt/storage01/data/.sxbackup/.temp.da96dc2032cb4320a1d88771f9b4ae05]
ERROR Transferring snapshot failed
```
I already installed the actually version of btrfs-sxbackup.

Does someone knows the solution?

**Comment by masc3d** [comment]
applied kernel / btrfs updates? 
what is `uname -a` and `btrfs version` of source / destination system

**Comment by 6485im43** [comment]
**Source system (Ubuntu 18.04.3 LTS):**
>uname -a
Linux server01 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

>btrfs version
btrfs-progs v4.15.1

**Destination system (Debian 9.11):**
>uname -a
Linux nas02 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3 (2019-09-02) x86_64 GNU/Linux

>btrfs version
btrfs-progs v4.7.3

The backups is running once a week und every weekend there will be installed updates. So btrfs and kernel updates were applied.

**Comment by masc3d** [comment]
there are known issues referring to send / receive compat between different btrfs / prog versions and I also have seen incremental backups stop working as btrfs / progs are updated.

try to enforce a full non-incremental snapshot by removing the latest backup on remote side and let me know if this resolves your issue.

**Comment by masc3d** [comment]
closing as issue is presumably resolved.
