### ISSUE TITLE
Btrfs-send resiliency in the presence of tcp connection drops

### ISSUE THREAD

**Issue by crass** [masc3d/btrfs-sxbackup#66]
I have a 500GB initial backup that I'm attempting to run where the network dies after ~30GB transferred. When the network comes back the TCP stream has been dropped and so the transfer of btrfs-send data cannot continue. From here the transfer must be initiated again from the beginning.  As far as I know, there is no way to resume an interrupted btrfs-send or btrfs-receive, unfortunately.  I have every reason to believe that I will not be able to transfer 500GB without experiencing a connection drop so I can't actually do a backup.  It does not appear that btrfs-sxbackup handles this well. Has there been any thought into a solution for this type of problem?

[ One solution](https://unix.stackexchange.com/a/565090/289039) to this problem, which is to write the btrfs-send data to a file, transfer the file, then do btrfs-receive on the transferred file. This then requires that the sender have at least as much free space as the size of the volume being transferred for the initial transfer. For the incremental backups this might not be a big issue, but I consider it a deal breaker for the initial transfer (I don't have that amount of free space...).

It would be nice if we could split btrfs-send data into smaller chunks that would have a high probability of sending successfully. Then if a chunk fails to send, we could re-send it.  However this is not as simple as it might first appear. A naive implementation of this might just split the btrfs-send data into say 1GB chunks and call btrfs-receive on each of those chunks. This can't be done because the GB boundary may be in the middle of a command. So the previous chunk will end on a partial command and the next chunk will start with what looks like garbage.

I see two solutions each with their own advantages and disadvantages
1. Have a minimal parser which parses btrfs-send output to make sure that chunks are always on command boundaries.
    * __Disadvantage__: Writing such a parser could introduce a lot of complexity to the code. A brief peek at the [design notes](https://btrfs.wiki.kernel.org/index.php/Design_notes_on_Send/Receive) suggests that its not that bad.
    * __Advantage__: In theory we should be able to run each chunk with a separate btrfs-receive instance (not in parallel!). However, we still have to take care to avoid chunk failures, which means we can't naively pipe chunks to btrfs-receive. This allows more resiliency if the machine reboots before the last chunk is processed (there are still problems if the reboot happens while btrfs-receive is processing a chunk)
    * The procedure would look something like this in a background process that will continue regardless of the connection state of the sender:
      1. Wait until integral chunk is found
      2. Run btrfs-receive on chunk
      3. Remove chunk
      4. Exit if EOT marker found
      5. Go back to 1.
2. Send btrfs-send chunks which blindly split data on some chunk size. Have a background process which verifies the integrity of received chunks before sending them via named pipe to a background btrfs-receive process.
    * __Disadvantage__: Long running btrfs-receive. If this process dies (eg. a machine reboot), before completing the transfer the backup must be started over from the beginning.
    * __Advantage__: Less complicated than first option.
    * The background process feeding chunks to btrfs-receive would look fairly similar to the one in option 1, except instead of running btrfs-receive on a chunk, it would send the data to the named pipe.

Option 1 is a trade-off of more complexity for more resiliency. My initial thought is that option 2 should be first pursued, and if later it is determined that option 1 is worth implementing then do that.

If btrfs-send is interrupted, we also need a way of getting back to where we were in creating and sending chunks. As far as I know, the only way to do this would be to start the btrfs-send from scratch and discard up to a particular desired byte offset. This assumes that btrfs-send runs with the same arguments are deterministic. Is this a bad assumption?

What are the chances of a pull request implementing option 1 or 2 being accepted?

**Comment by masc3d** [comment]
btrfs send / receive itself does not support resume. 

it would be possible to implement this (by send/receiving to local file chunks and rsyncing those instead) but it would be quite complex to implement. given that this is presumaby a rather rare use case, I dont see this happen anytime soon, if at all.
