### ISSUE TITLE
Enable compression on destination only

### ISSUE THREAD

**Issue by MurzNN** [masc3d/btrfs-sxbackup#68]
Is it possible to enable compression on destination drive only, with keeping source without compression?
I see that with default arguments `init` command shows "compress" separately for each location:
```
# btrfs-sxbackup init /var/lib/mysql /var/backups/mysql
INFO btrfs-sxbackup v0.6.11
INFO preparing source and destination environment
INFO source :: url [/var/lib/mysql/] container [.sxbackup/] retention [3] compress [False]
INFO destination :: url [/var/backups/mysql/] retention [2d: 1/d, 2w:3/w, 1m:1/w, 2m:none] compress [False]
INFO initialized successfully
```
But see no options to pass `compress` argument for destination (and for source too), there is `--compress` option bit it is only for transmission process.

**Comment by masc3d** [comment]
yes `compress` is only for transmission. 
since there's no transmission for local (source) snapshot there's also no compression.

**Comment by MurzNN** [comment]
So, can we enable compression for destination storage (compress files stored in target btrfs filesystem, to make keeping backups more compact), or it is impossible because of btrfs can store transferred clone of snapshot only in same format?

The idea is to keep source btrfs filesystem without compression (for performance reasons), but compress data on destination storage.

**Comment by masc3d** [comment]
you should be able to use btrfs compression on any subvolume, yes.
it's not related to `btrfs-sxbackup` `compress` option, which only affects transmission.

**Comment by MurzNN** [comment]
Yeah, this works, thanks for information!
```
# compsize /var/lib/mysql
Processed 12098 files, 118059 regular extents (346310 refs), 43 inline.
Type       Perc     Disk Usage   Uncompressed Referenced  
TOTAL      100%       24G          24G          73G       
none       100%       24G          24G          73G       

# compsize /var/backups/mysql/
Processed 8065 files, 203886 regular extents (406165 refs), 59 inline.
Type       Perc     Disk Usage   Uncompressed Referenced  
TOTAL       15%      3.7G          24G          49G       
none       100%      168M         168M         337M       
zstd        14%      3.5G          24G          48G       
```

The confusing thing was the `compress [False]` on `btrfs-sxbackup init` output of destination line, even when destination drive is mounted with `compress=zstd` option
