### ISSUE TITLE
Missing destination url in ssh source .sxbackup/.btrfs-sxbackup config file

### ISSUE THREAD

**Issue by MurzNN** [masc3d/btrfs-sxbackup#72]
I trying to create a backup of remote btrfs volume via ssh, so launch command like this:
```
root@backup-server# btrfs-sxbackup init -sr "3" -dr "1d:1/d, 1w:daily, 2w:daily, 3w:daily, 4w:daily, 5w:none" ssh://root@remote-server/opt/docker/solr /var/backups/solr
INFO btrfs-sxbackup v0.6.11
INFO preparing source and destination environment
INFO source :: url [ssh://root@remote-server/opt/docker/solr] container [.sxbackup/] retention [3] compress [False]
INFO destination :: url [/var/backups/solr/] retention [1d:1/d, 1w:daily, 2w:daily, 3w:daily, 4w:daily, 5w:none] compress [False]
INFO initialized successfully
```
But, as result, I see no `destination` info on source btrfs volume:
```
root@remote-server# cat /opt/docker/solr/.sxbackup/.btrfs-sxbackup
[Source]
uuid = 14efdee7-ec3c-4c12-9875-439caefdxxxx
retention = 3
```
Here is contents of config file in destination:
```
root@backup-server# cat /var/backups/solr/.btrfs-sxbackup
[Destination]
uuid = 14efdee7-ec3c-4c12-9875-439caefdfa6e
source = ssh://root@remote-server/opt/docker/solr/
source-container = .sxbackup/
retention = 1d:1/d, 1w:daily, 2w:daily, 3w:daily, 4w:daily, 5w:none
```
And a `run` command do the backup only on remote source, without transferring it to local destination:
```
root@backup-server# btrfs-sxbackup run ssh://root@remote-server/opt/docker/solr
INFO btrfs-sxbackup v0.6.11
INFO source :: url [ssh://root@remote-server/opt/docker/solr/] container [.sxbackup/] retention [3] compress [False]
INFO preparing environment
INFO source :: retrieving snapshots
INFO source :: creating snapshot
INFO backup sx-20210901-183125-utc created successfully in 00:00:01
```

Where can be the problem?

**Comment by MurzNN** [comment]
In configurations where source and destination are in local machine - all works well, in source's `/.sxbackup/.btrfs-sxbackup` there is `destination` exists:
```
# cat /var/lib/mysql/.sxbackup/.btrfs-sxbackup
[Source]
uuid = c2c8fe73-6ee9-45f0-9698-81af8a9fxxxx
source = /var/lib/mysql/
source-container = .sxbackup/
destination = /var/backups/brick/brick-svs/mysql/
retention = 3

**Comment by masc3d** [comment]
yes, it works as expected.
when setting up a pull job (source is remote url, destination is local path) the destination url is unknown, thus it cannot be set. for pull jobs that's also not required.

**Comment by MurzNN** [comment]
If that is OK, why the "run" job doesn't transfer source snapshot on remote host to destination on local host? Maybe I need to pass some special argument to do this?

**Comment by bhelm** [comment]
`btrfs-sxbackup run /var/backups/solr` is what you are looking for. btrfs-sxbackup then looks into the [Destination] definition on the backup server and knows where the source is. The source than just contains the uuid and a retention rule.

**Comment by MurzNN** [comment]
Yeah, that works, thanks @bhelm! Will be good to describe this trick in documentation...

**Comment by MurzNN** [comment]
I made a PR with documentation improvement about this: https://github.com/masc3d/btrfs-sxbackup/pull/73
