### ISSUE TITLE
documentation clarification

### ISSUE THREAD

**Issue by ian-kelling** [masc3d/btrfs-sxbackup#8]
This is maybe more of a vague feature request. I read your docs, and had these observations: Where is this storing configuration about the jobs? Seems like something that someone considering using a utility like this would generally like to know. I see it's in the bottom, in the changelog. And, if I'm not supposed to interact with the config, how can Iist out the existing jobs? Regarding this line: "or more complex expression like ..." it implies there is further documentation elsewhere, but I don't see anything. Are those the only time intervals? Is there a way to specify unlimited number of backups?

**Comment by masc3d** [comment]
yes thanks, I may intended to add some more infos at some point. until then you can use -vvv to see exactly what btrfs-sxbackup is doing. most documentation is maintained in the source, for some more info have a look at retention.py. the management of backup jobs is up to you, as each job is represented by a btrfs subvolume, you can easily use btrfs sub list with grep etc. to view all the jobs in the system and also freely organize them as you like.
